# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AddHorseWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(622, 296)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 10, 571, 241))
        self.widget.setObjectName("widget")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.horseName = QtWidgets.QTextEdit(self.widget)
        self.horseName.setObjectName("horseName")
        self.verticalLayout.addWidget(self.horseName)
        self.verticalLayout_10.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_2.addWidget(self.label_4)
        self.horseBreed = QtWidgets.QTextEdit(self.widget)
        self.horseBreed.setObjectName("horseBreed")
        self.verticalLayout_2.addWidget(self.horseBreed)
        self.verticalLayout_10.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.sexHorse = QtWidgets.QTextEdit(self.widget)
        self.sexHorse.setObjectName("sexHorse")
        self.verticalLayout_3.addWidget(self.sexHorse)
        self.verticalLayout_10.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout_10)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_5.addWidget(self.label_7)
        self.horseParents = QtWidgets.QTextEdit(self.widget)
        self.horseParents.setObjectName("horseParents")
        self.verticalLayout_5.addWidget(self.horseParents)
        self.verticalLayout_11.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_4.addWidget(self.label_6)
        self.feedingHorse = QtWidgets.QTextEdit(self.widget)
        self.feedingHorse.setObjectName("feedingHorse")
        self.verticalLayout_4.addWidget(self.feedingHorse)
        self.verticalLayout_11.addLayout(self.verticalLayout_4)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_6.addWidget(self.label_8)
        self.feedingTypeHorse = QtWidgets.QTextEdit(self.widget)
        self.feedingTypeHorse.setObjectName("feedingTypeHorse")
        self.verticalLayout_6.addWidget(self.feedingTypeHorse)
        self.verticalLayout_11.addLayout(self.verticalLayout_6)
        self.horizontalLayout_2.addLayout(self.verticalLayout_11)
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_8.addWidget(self.label_10)
        self.feedingHours = QtWidgets.QTextEdit(self.widget)
        self.feedingHours.setObjectName("feedingHours")
        self.verticalLayout_8.addWidget(self.feedingHours)
        self.verticalLayout_12.addLayout(self.verticalLayout_8)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_7.addWidget(self.label_9)
        self.quantityHorse = QtWidgets.QTextEdit(self.widget)
        self.quantityHorse.setObjectName("quantityHorse")
        self.verticalLayout_7.addWidget(self.quantityHorse)
        self.verticalLayout_12.addLayout(self.verticalLayout_7)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_9.addWidget(self.label_11)
        self.medicamentsHorse = QtWidgets.QTextEdit(self.widget)
        self.medicamentsHorse.setObjectName("medicamentsHorse")
        self.verticalLayout_9.addWidget(self.medicamentsHorse)
        self.verticalLayout_12.addLayout(self.verticalLayout_9)
        self.horizontalLayout_2.addLayout(self.verticalLayout_12)
        self.verticalLayout_13.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(388, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.backButton = QtWidgets.QPushButton(self.widget)
        self.backButton.setObjectName("backButton")
        self.horizontalLayout.addWidget(self.backButton)
        self.addButton = QtWidgets.QPushButton(self.widget)
        self.addButton.setObjectName("addButton")
        self.horizontalLayout.addWidget(self.addButton)
        self.verticalLayout_13.addLayout(self.horizontalLayout)
        self.errorLabel = QtWidgets.QLabel(self.widget)
        self.errorLabel.setObjectName("errorLabel")
        self.verticalLayout_13.addWidget(self.errorLabel)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Name"))
        self.label_4.setText(_translate("MainWindow", "breed"))
        self.label_5.setText(_translate("MainWindow", "sex"))
        self.label_7.setText(_translate("MainWindow", "Parents"))
        self.label_6.setText(_translate("MainWindow", "Feeding"))
        self.label_8.setText(_translate("MainWindow", "Feeding type"))
        self.label_10.setText(_translate("MainWindow", "Feeding hours"))
        self.label_9.setText(_translate("MainWindow", "Quantity"))
        self.label_11.setText(_translate("MainWindow", "Medicaments"))
        self.backButton.setText(_translate("MainWindow", "Back"))
        self.addButton.setText(_translate("MainWindow", "Add"))
        self.errorLabel.setText(_translate("MainWindow", "No errors"))


class AddHorseWindow(QtWidgets.QMainWindow):

    def __init__(self, mainMenu, stable):
        super(AddHorseWindow, self).__init__()

        self.mainMenu = mainMenu
        self.stable = stable
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        self.ui.backButton.clicked.connect(self.back_to_main_menu)
        self.ui.addButton.clicked.connect(self.add_to_object)

    def back_to_main_menu(self):
        self.hide()
        self.mainMenu.show()


    def add_to_object(self):
        horse_name = self.ui.horseName.toPlainText()
        horse_breed = self.ui.horseBreed.toPlainText()
        horse_sex = self.ui.sexHorse.toPlainText()
        horse_parents = self.ui.horseParents.toPlainText()
        horse_feeding = self.ui.feedingHorse.toPlainText()
        horse_feeding_type = self.ui.feedingTypeHorse.toPlainText()
        horse_feeding_hours = self.ui.feedingHours.toPlainText()
        quantity = self.ui.quantityHorse.toPlainText()
        medicaments = self.ui.medicamentsHorse.toPlainText()

        if quantity =='':
            quantity = 1

        result = self.stable.addHorse(horse_name, horse_breed, horse_sex, horse_parents, horse_feeding, horse_feeding_type, horse_feeding_hours, quantity, medicaments)
        if -1 == result:
            self.ui.errorLabel.setText("You have passed wrong values !!!! Try again. It is probably quantity value")
        else:
            self.hide()
            self.mainMenu.show()
